thing = input('Digite algo: ')
print(f'O tipo primitivo desse valor é : {type(thing)}')
print(f'Só tem espaços? {thing.isspace()}')
print(f'É um número? {thing.isnumeric()}')
print(f'É alfabético? {thing.isalpha()}')
print(f'É alfanumérico? {thing.isalnum()}')
print(f'Está em maiúsculas? {thing.isupper()}')
print(f'Está em minúsculas? {thing.islower()}')
print(f'Está capitalizada? {thing.istitle()}')
